-- MySQL Script generated by MySQL Workbench
-- 07/04/17 01:14:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database_EBA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_EBA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_EBA` DEFAULT CHARACTER SET utf8 ;
USE `database_EBA` ;

-- -----------------------------------------------------
-- Table `database_EBA`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`empresa` (
  `nropatronal` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `nit` BIGINT(15) NOT NULL,
  `tipo_empresa` VARCHAR(50) NULL,
  PRIMARY KEY (`nropatronal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`sucursal` (
  `codigo` VARCHAR(10) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `e_mail` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `nropatronal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_sucursal_empresa_idx` (`nropatronal` ASC),
  CONSTRAINT `fk_sucursal_empresa`
    FOREIGN KEY (`nropatronal`)
    REFERENCES `database_EBA`.`empresa` (`nropatronal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`trabajador` (
  `ci` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `paterno` VARCHAR(30) NOT NULL,
  `materno` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `codsucursal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ci`),
  INDEX `fk_trabajador_sucursal_idx` (`codsucursal` ASC),
  CONSTRAINT `fk_trabajador_sucursal`
    FOREIGN KEY (`codsucursal`)
    REFERENCES `database_EBA`.`sucursal` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`beneficiario` (
  `ci` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `paterno` VARCHAR(30) NOT NULL,
  `materno` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`avala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`avala` (
  `citrabajador` INT NOT NULL,
  `cibeneficiario` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_avala_beneficiario_idx` (`cibeneficiario` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_avala_trabajador`
    FOREIGN KEY (`citrabajador`)
    REFERENCES `database_EBA`.`trabajador` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avala_beneficiario`
    FOREIGN KEY (`cibeneficiario`)
    REFERENCES `database_EBA`.`beneficiario` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`planificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`planificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `cibeneficiario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_planificacion_beneficiario_idx` (`cibeneficiario` ASC),
  CONSTRAINT `fk_planificacion_beneficiario`
    FOREIGN KEY (`cibeneficiario`)
    REFERENCES `database_EBA`.`beneficiario` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`almacen` (
  `codigo` VARCHAR(10) NOT NULL,
  `departamento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` INT NOT NULL,
  `e_mail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`empleado` (
  `ci` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `codalmacen` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ci`),
  INDEX `fk_empleado_almacen_idx` (`codalmacen` ASC),
  CONSTRAINT `fk_empleado_almacen`
    FOREIGN KEY (`codalmacen`)
    REFERENCES `database_EBA`.`almacen` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`nota_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`nota_entrega` (
  `nro` INT NOT NULL AUTO_INCREMENT,
  `mes_correspondiente` VARCHAR(15) NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `ciempleado` INT NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`nro`),
  INDEX `fk_nota_entrega_empleado_idx` (`ciempleado` ASC),
  CONSTRAINT `fk_nota_entrega_empleado`
    FOREIGN KEY (`ciempleado`)
    REFERENCES `database_EBA`.`empleado` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`paquete` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_planificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_planificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `periodo_inicio` DATE NOT NULL,
  `periodo_fin` DATE NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  `codpaquete` INT NOT NULL,
  `idplanificacion` INT NOT NULL,
  `codalmacen` VARCHAR(10) NOT NULL,
  `nroentrega` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_planificacion_planificacion_idx` (`idplanificacion` ASC),
  INDEX `fk_detalle_planificacion_nota_entrega_idx` (`nroentrega` ASC),
  INDEX `fk_detalle_planificacion_paquete_idx` (`codpaquete` ASC),
  INDEX `fk_detalle_planificacion_almacen_idx` (`codalmacen` ASC),
  CONSTRAINT `fk_detalle_planificacion_planificacion`
    FOREIGN KEY (`idplanificacion`)
    REFERENCES `database_EBA`.`planificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_planificacion_nota_entrega`
    FOREIGN KEY (`nroentrega`)
    REFERENCES `database_EBA`.`nota_entrega` (`nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_planificacion_paquete`
    FOREIGN KEY (`codpaquete`)
    REFERENCES `database_EBA`.`paquete` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_planificacion_almacen`
    FOREIGN KEY (`codalmacen`)
    REFERENCES `database_EBA`.`almacen` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`pendiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`pendiente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `nroentrega` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pendiente_nota_entrega_idx` (`nroentrega` ASC),
  CONSTRAINT `fk_pendiente_nota_entrega`
    FOREIGN KEY (`nroentrega`)
    REFERENCES `database_EBA`.`nota_entrega` (`nro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`proveedor` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `departamento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `e_mail` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`producto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio_compra` DECIMAL(12,2) NOT NULL,
  `precio_venta` DECIMAL(12,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `idcategoria` INT NOT NULL,
  `codproveedor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_producto_categoria_idx` (`idcategoria` ASC),
  INDEX `fk_producto_proveedor_idx` (`codproveedor` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `database_EBA`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_proveedor`
    FOREIGN KEY (`codproveedor`)
    REFERENCES `database_EBA`.`proveedor` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_paquete` (
  `codpaquete` INT NOT NULL,
  `codproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_paquete_producto_idx` (`codproducto` ASC),
  CONSTRAINT `fk_detalle_paquete_paquete`
    FOREIGN KEY (`codpaquete`)
    REFERENCES `database_EBA`.`paquete` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_paquete_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_pendiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_pendiente` (
  `codproducto` INT NOT NULL,
  `idpendiente` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codproducto`, `idpendiente`),
  INDEX `fk_detalle_pendiente_pendiente_idx` (`idpendiente` ASC),
  CONSTRAINT `fk_detalle_pendiente_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_pendiente_pendiente`
    FOREIGN KEY (`idpendiente`)
    REFERENCES `database_EBA`.`pendiente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`inventario` (
  `codproducto` INT NOT NULL,
  `codalmacen` VARCHAR(10) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`codproducto`, `codalmacen`),
  INDEX `fk_inventario_almacen_idx` (`codalmacen` ASC),
  CONSTRAINT `fk_inventario_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventario_almacen`
    FOREIGN KEY (`codalmacen`)
    REFERENCES `database_EBA`.`almacen` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`orden_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`orden_pedido` (
  `nro` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `nota` VARCHAR(50) NULL,
  `vigencia` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `codproveedor` VARCHAR(10) NOT NULL,
  `codalmacen` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nro`),
  INDEX `fk_orden_pedido_almacen_idx` (`codalmacen` ASC),
  INDEX `fk_orden_pedido_proveedor_idx` (`codproveedor` ASC),
  CONSTRAINT `fk_orden_pedido_almacen`
    FOREIGN KEY (`codalmacen`)
    REFERENCES `database_EBA`.`almacen` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orden_pedido_proveedor`
    FOREIGN KEY (`codproveedor`)
    REFERENCES `database_EBA`.`proveedor` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_orden_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_orden_pedido` (
  `nropedido` INT NOT NULL,
  `codproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`nropedido`, `codproducto`),
  INDEX `fk_detalle_pedido_producto_idx` (`codproducto` ASC),
  CONSTRAINT `fk_detalle_pedido_orden_pedido`
    FOREIGN KEY (`nropedido`)
    REFERENCES `database_EBA`.`orden_pedido` (`nro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_pedido_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`nota_remision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`nota_remision` (
  `codigo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `codproveedor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_nota_remision_proveedor_idx` (`codproveedor` ASC),
  CONSTRAINT `fk_nota_remision_proveedor`
    FOREIGN KEY (`codproveedor`)
    REFERENCES `database_EBA`.`proveedor` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`devolucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `codremision` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devolucion_nota_remision_idx` (`codremision` ASC),
  CONSTRAINT `fk_devolucion_nota_remision`
    FOREIGN KEY (`codremision`)
    REFERENCES `database_EBA`.`nota_remision` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_devolucion` (
  `iddevolucion` INT NOT NULL,
  `codproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`iddevolucion`, `codproducto`),
  INDEX `fk_detalle_devolucion_producto_idx` (`codproducto` ASC),
  CONSTRAINT `fk_detalle_devolucion_devolucion`
    FOREIGN KEY (`iddevolucion`)
    REFERENCES `database_EBA`.`devolucion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_devolucion_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`nota_recepcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`nota_recepcion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `nropedido` INT NOT NULL,
  `codremision` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_nota_recepcion_orden_pedido_idx` (`nropedido` ASC),
  INDEX `fk_nota_recepcion_nota_remision_idx` (`codremision` ASC),
  CONSTRAINT `fk_nota_recepcion_orden_pedido`
    FOREIGN KEY (`nropedido`)
    REFERENCES `database_EBA`.`orden_pedido` (`nro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_nota_recepcion_nota_remision`
    FOREIGN KEY (`codremision`)
    REFERENCES `database_EBA`.`nota_remision` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_nota_remision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_nota_remision` (
  `codremision` INT NOT NULL,
  `codproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`codremision`, `codproducto`),
  INDEX `fk_detalle_remision_producto_idx` (`codproducto` ASC),
  CONSTRAINT `fk_detalle_remision_nota_remision`
    FOREIGN KEY (`codremision`)
    REFERENCES `database_EBA`.`nota_remision` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_remision_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`lote` (
  `codigo` VARCHAR(10) NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `tipo_envase` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_EBA`.`detalle_nota_recepcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_EBA`.`detalle_nota_recepcion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  `codrecepcion` INT NOT NULL,
  `codproducto` INT NOT NULL,
  `codlote` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_detalle_recepcion_producto_idx` (`codproducto` ASC),
  INDEX `fk_detalle_recepcion_nota_recepcion_idx` (`codrecepcion` ASC),
  INDEX `fk_detalle_recepcion_lote_idx` (`codlote` ASC),
  CONSTRAINT `fk_detalle_recepcion_producto`
    FOREIGN KEY (`codproducto`)
    REFERENCES `database_EBA`.`producto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_recepcion_nota_recepcion`
    FOREIGN KEY (`codrecepcion`)
    REFERENCES `database_EBA`.`nota_recepcion` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_recepcion_lote`
    FOREIGN KEY (`codlote`)
    REFERENCES `database_EBA`.`lote` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
